FROM alpine:latest

RUN apk add --no-cache docker-cli msmtp curl

COPY alert.sh /alert.sh
COPY entrypoint.alerter.sh /entrypoint.sh
RUN chmod +x /alert.sh /entrypoint.sh

# Check for stale X auth every 15 minutes
ENTRYPOINT ["/entrypoint.sh"]
