services:
  touitomamout:
    container_name: "touitomamout"
    image: ghcr.io/yamada-sexta/touitomamout-next:latest
    restart: unless-stopped
    env_file: ".env"
    environment:
      - DATABASE_PATH=/data/database.sqlite
    volumes:
      - ./data:/data

  updater:
    image: ghcr.io/ryanscharf/touitomamout-next-updater:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/docker-compose.yml
      - ./data:/var/lib/touitomamout

  alerter:
    image: ghcr.io/ryanscharf/touitomamout-next-alerter:latest
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./alert-data:/var/lib/touitomamout-alert
